### ISSUE TITLE
Does base embedding only update when sending aggregate graph?

### ISSUE THREAD

**Issue by Yujun-Yan** [HKUST-KnowComp/MNE#10]
Hi, I have a question about your code.
Correct me if I am wrong. It seems that you use the base_weight to control whether to update the vectors. But base vectors are updated only when base_weight=0, that means, your base vector is not co-learned with the local vectors and the transition matrix, right? So you first compute the base vectors using the aggregate graph(base network in your code) and then compute local vectors and transition matrix for other graphs? Or do I miss something?

**Comment by panda0881** [comment]
Dear Yujun,

Yes, we train the base network first. As this code was originally used for
the tencent data, which has a base friendship network.

Best regards,
Hongming

Yujun-Yan <notifications@github.com> 于 2018年8月25日周六 上午5:14写道：

**Comment by Yujun-Yan** [comment]
OK. But in the later training, why do we not update the base weight? since the base weight is set to 0.

**Comment by panda0881** [comment]
As this code was originally used for the social network and for the social network, as we introduced in the paper, we use the friendship relation as the base network, which is the most important (we believe) relation between users and we do not want the base network to lose that property during the training process. That is why we keep it unchanged during the training process and only use the additional vecter to record the additional information. For other networks, you can view it as a hyper-parameter and tune it based on your need.

Best regards,
Hongming
________________________________
发件人: Yujun-Yan <notifications@github.com>
发送时间: 2018年8月25日 8:22:25
收件人: HKUST-KnowComp/MNE
抄送: Hongming ZHANG; Comment
主题: Re: [HKUST-KnowComp/MNE] Does base embedding only update when sending aggregate graph? (#10)


OK. But in the later training, why do we not update the base weight? since the base weight is set to 0.

―
