### ISSUE TITLE
How to adapt with our own method of embedding ?

### ISSUE THREAD

**Issue by LPioL** [HKUST-KnowComp/MNE#17]
Hello,

I have my own method of multiplex network embedding and I would like to test it on link prediction and compare it with your method. My embedding method needs the whole training multiplex graph.
How can I use the same graph for training ? I am a bit confused which data I have to use.
For example, line 457 in main.py, I don't understand why training_data_by_type['Base'] has more entries than edges in Vickers.edges.

Thank you

**Comment by panda0881** [comment]
Hi,

Sorry for the late reply, I am not sure I understand your question correctly. Do you mean you have an embedding and want to test its performance on the multiplex dataset? If you ignore the edge information, you can simply use all the edges as a whole, otherwise, you need to test its performance on different kinds of relations separately.

Best Regards,
Hongming

**Comment by LPioL** [comment]
Yes and I don't train my method graph by graph like MNE or node2vec. Anyway I found a way to use your code to test my embedding using the training/test graph used for PMNE.
Nevertheless, I tested your method on LAZEGA multiplex network but I didn't find the same result (0.839 for your article; 0.79 for me). What are the parameters did you use ?

Best regards

**Comment by panda0881** [comment]
I think I used the same hyper-parameter for all the datasets, which is the default one provided in this repo. How about the others?

Best Regards,
Hongming

**Comment by LPioL** [comment]
I had ti reduce the variable 'iter' to 10, otherwise with 100 I had errors. For C ELEGANS I have the same results.

Best,

Léo
