### ISSUE TITLE
Does this program work only with directed graphs ?

### ISSUE THREAD

**Issue by eneszv** [HKUST-KnowComp/MNE#18]
From the data/###.edges file it is evident that this example graph is directed. If I want to use an undirected graph, do I need to make for every edge "a--b" one more edge "b--a" in edge list file?

From the 262. line in MNE.py, there is parameter `directed = False` but in your example, you have directed graph. Further, in line 331. it says:

_`directed` = if False (default), take neighbour from two directions, if True, take neighbour from one direction._

Does this mean if we want to use a directed graph, we use `directed = False` and vice versa, if we have undirected graph we change `directed = True` ?

**Comment by panda0881** [comment]
Hi Enes,

By default, we didn't consider the edge direction, which means that we treat the graph as undirected. Yes, you can change that by switching 'directed' to True. Actually, this setting only influences the random walk process. To be honest, I think current network embeddings may not effectively preserve the direction information because their training loss is based on co_occurrence information.

Best Regards,
Hongming
